# Generated by Django 5.0.1 on 2024-05-24 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='C:/Users/israe/Documents')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.maison')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lieux', models.CharField(max_length=255)),
                ('date_arrivee', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.maison')),
            ],
        ),
    ]
